// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUsR9fCtbLBbdjuQ723LaEXngvvvCADAI',
    appId: '1:61883152270:web:80972aee8f43d024ca16df',
    messagingSenderId: '61883152270',
    projectId: 'last-proj-18359',
    authDomain: 'last-proj-18359.firebaseapp.com',
    storageBucket: 'last-proj-18359.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1nxPv-m8mRA3NPMHnjPuO4RQR5hmRV48',
    appId: '1:61883152270:android:83bf60053461e8a3ca16df',
    messagingSenderId: '61883152270',
    projectId: 'last-proj-18359',
    storageBucket: 'last-proj-18359.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAA1KVRHtXVbTWwvqkSjNoxHcuT1MrK_E',
    appId: '1:61883152270:ios:53d2136789bf8ab9ca16df',
    messagingSenderId: '61883152270',
    projectId: 'last-proj-18359',
    storageBucket: 'last-proj-18359.appspot.com',
    iosClientId: '61883152270-kic5hf1mum4059smoh7tie959mlno2fc.apps.googleusercontent.com',
    iosBundleId: 'com.example.last',
  );
}
